version: "3"

services:
    db:
        image: mariadb:10.5
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        env_file: .env
    
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8000:80"
        restart: unless-stopped
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: $MYSQL_USER
            WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
            WORDPRESS_DB_NAME: $MYSQL_DATABASE
            WP_DEBUG: "true"
        volumes:
            - ./wordpress:/var/www/html/
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
    db_data: {}
