version: "3"

services:
    db:
        container_name: db
        image: mariadb:10.5
        volumes:
            - "db_data:/var/lib/mysql"
        restart: always
        env_file: .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    
    wordpress:
        container_name: wordpress
        depends_on:
            - db
        build: "./config/containers"
        ports:
            - "8000:80"
        restart: always
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER:-root}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-password}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
            WORDPRESS_DEBUG: "true"
        volumes:
            - "./wordpress:/var/www/html/"
            - "./plugins:/var/www/html/wp-content/plugins"
            - "./themes:/var/www/html/wp-content/themes"
            - "./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"

volumes:
    db_data: {}
