version: "3"

services:
    db:
        container_name: db
        image: mariadb:10.5
        volumes:
            - "db_data:/var/lib/mysql"
        restart: always
        env_file: .env

    wordpress:
        container_name: wordpress
        depends_on:
            - db
        build: "./config/wordpress"
        ports:
            - "8000:80"
        restart: always
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: $MYSQL_USER
            WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
            WORDPRESS_DB_NAME: $MYSQL_DATABASE
            WORDPRESS_DEBUG: "true"
        volumes:
            - "./wordpress:/var/www/html/"
            - "./plugins:/var/www/html/wp-content/plugins"
            - "./themes:/var/www/html/wp-content/themes"
            - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"

volumes:
    db_data: {}
