#!/bin/bash
#
# Checks for required configs then starts Docker containers.

#######################################
# Runs the ./bin/make shell script.
# Arguments:
#   None
# Outputs:
#   Creates the ./.env file
#######################################
set_up_env_file() {
  echo 'First run: Setting up environment file...'
  # shellcheck disable=SC1091
  source ./bin/make
}

#######################################
# Creates the WP container Dockerfile.
# Arguments
#   None
# Outputs:
#   Creates the Dockerfile and writes RUN commands to it
#######################################
set_up_dockerfile() {
	local user_id
  local group_id

  if ! cp './config/containers/Dockerfile.template' './config/containers/Dockerfile'; then
    echo -e "Unable to copy Dockerfile in config." >&2
    exit 1
  else
    echo -e "Copied WordPress container Dockerfile."
  fi

  user_id="$(id -u)"
	group_id="$(id -g)"

  echo -e "\nRUN usermod -u ${user_id} www-data" >> './config/containers/Dockerfile'
  echo -e "RUN groupmod -o -g ${group_id} www-data" >> './config/containers/Dockerfile'
}

#######################################
# Calls Docker Compose to start containers.
# Arguments:
#   None
#######################################
start_docker() {
  local containers

  # TODO support muliple containers.
  containers='wordpress'

  echo -e 'Starting Docker containers...'

  docker-compose up --detach "${containers}"
  if (( $? != 0 )); then
    echo -e 'Failed to start Docker containers. See terminal output for errors.'
    exit 1
  fi

  docker exec -ti wordpress /bin/bash -c 'chown -R www-data: /var/www/html'

  while [[ -z "${ready}" ]]; do
    if curl -I http://localhost:8000 2>/dev/null | grep -q -e "HTTP/1.1 200 OK" -e "HTTP:/1.1 302 Found"; then
      ready=true
    else
      sleep 4
      echo 'Waiting for network to boot...'
    fi
  done

  echo -e 'All set!'
}

#######################################
# Starts the script.
# Arguments:
#   None
#######################################
main() {
  if [[ ! -f './.env' ]]; then
    set_up_env_file
  fi

  if [[ ! -f './config/containers/Dockerfile' ]]; then
    set_up_dockerfile
  fi

  start_docker
}

main "$@"
